apiVersion: v1
kind: Service
metadata:
  namespace: anatheobald
  name: frontend-api
spec:
  type: NodePort
  selector:
    app: frontend-api
  ports:
    - port: 80
      targetPort: 50001  # ← Change this to match Flask port
      nodePort: 50001