apiVersion: batch/v1
kind: Job
metadata:
  namespace: anatheobald
  name: ml-generator-job
  # generateName: ml-generator-job-
  labels:
    app: ml-generator
  annotations:
    # argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: ml-generator
          image: quay.io/anatheobald/ml-generator:97846ef
          env:
            - name: DATASET_PATH
              valueFrom:
                configMapKeyRef:
                  name: ml-generator-config
                  key: DATASET_PATH             
            - name: DATASET_VERSION
              valueFrom:
                configMapKeyRef:
                  name: ml-generator-config
                  key: DATASET_VERSION             
            - name: MIN_SUPPORT
              value: "0.05"
            - name: MIN_CONFIDENCE
              value: "0.5"
            - name: OUT
              value: "/model/rules.pkl"
            - name: OUT_JSON
              value: "/model/rules.json"
            - name: FRONTEND_IP
              value: "10.43.127.130"
          volumeMounts:
            - name: spotify-dataset
              mountPath: /data
            - name: model-volume
              mountPath: /model
      restartPolicy: Never
      volumes:
        - name: spotify-dataset
          hostPath:
            path: /home/datasets/spotify
            type: Directory
        - name: model-volume
          persistentVolumeClaim:
            claimName: project2-pvc-anatheobald
