apiVersion: batch/v1
kind: Job
metadata:
  name: redeploy-frontend
  namespace: anatheobald
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: redeploy
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Restarting frontend-api deployment..."
              kubectl rollout restart deployment/frontend-api -n anatheobald
